package emacs

// Note that this file contains stubs, not actual
// implementation. Real code is generated by the compiler.

// Funcall invokes Elisp function.
//
// Function existance or signature compatibility is
// not checked during compilation.
// If something is wrong, Emacs will complain during evaluation.
func Funcall(fn Symbol, args ...Object) Object {
	return nil
}
