package symbols

import (
	"fmt"
)

const (
	symPrefix        = "goism-"
	symPrivatePrefix = "goism--"
)

// Mangle returns a Emacs-style public symbol name.
// Mangle("pkg", "name") => "goism-pkg.name".
func Mangle(pkgPath string, name string) string {
	return fmt.Sprintf("%s%s.%s", symPrefix, pkgPath, name)
}

// MangleMethod is like Mangle, but intended to be used for method names.
// MangleMethod("pkg", "recv", "name") => "goism-pkg.recv.name"
func MangleMethod(pkgPath string, recv string, name string) string {
	return Mangle(pkgPath, recv+"."+name)
}

// ManglePriv returns a Emacs-style private symbol name.
// Used for symbols that are automatically generated by the goism.
// ManglePriv("pkg", "name") => "goism--pkg.name".
func ManglePriv(pkgPath string, name string) string {
	return fmt.Sprintf("%s%s.%s", symPrivatePrefix, pkgPath, name)
}
