package lisp

// Note that this file contains stubs, not actual
// implementations. Real code is generated by the compiler.

// Call invokes Elisp function.
//
// Function existance or signature compatibility is
// not checked during compilation.
// If something is wrong, Emacs will complain during evaluation.
func Call(fn Symbol, args ...Object) Object {
	return nil
}

// Intern returns the canonical symbol with specified name.
// If there is none, new is created.
func Intern(name string) Symbol {
	return Symbol{}
}
