package lisp

/*
	Types
*/

// Object is unboxed Emacs Lisp object.
type Object interface {
	object()
}

type (
	Int    int
	Float  float64
	String string
	Symbol string
)

/*
	Functions
*/

// Note that this file contains stubs, not actual
// implementations. Real code is generated by the compiler.

// Call invokes Elisp function.
//
// Function existance or signature compatibility is
// not checked during compilation.
// If something is wrong, Emacs will complain during evaluation.
func Call(fn Symbol, args ...Object) Object {
	return nil
}
